import { Meal } from './meal';

export const MEALS: Meal[] = [
	{ 
		id: 1,
		date: 'Monday, 21 June', 
		name:'',
		s_calories:0,
		s_carb:0,
		f_kcal: 30,
		s_kcal: 100, 
		t_kcal: 200, 
		f_carbs: 500, 
		s_carbs: 50, 
		t_carbs: 200, 
		f_fat: 50,
		s_fat: 10,
		t_fat: 70,
		f_protein: 90, 
		s_protein: 30, 
		t_protein: 50, 
		photo1: 'assets/img/photo1.png', 
		photo2: 'assets/img/meal1.png',
		photo3: 'assets/img/meal2.png',
		doneState1: true,
		doneState2: false,
		doneState3: false,
		change1: false,
		change2: false,
		change3: false
	},
	{ 
		id: 2,
		date: 'Tuesday, 22 June',
		name:'',
		s_calories:0,
		s_carb:0,
		f_kcal: 30,
		s_kcal: 100, 
		t_kcal: 200, 
		f_carbs: 500, 
		s_carbs: 50, 
		t_carbs: 200, 
		f_fat: 50,
		s_fat: 10,
		t_fat: 70,
		f_protein: 90, 
		s_protein: 30, 
		t_protein: 50, 
		photo1: 'assets/img/meal3.png', 
		photo2: 'assets/img/meal5.png',
		photo3: 'assets/img/photo1.png',
		doneState1: false,
		doneState2: false,
		doneState3: true,
		change1: false,
		change2: false,
		change3: false
	},
	{ 
		id: 3,
		date: 'Wednesday, 23 June',
		name:'',
		s_calories:0,
		s_carb:0,
		f_kcal: 30,
		s_kcal: 100, 
		t_kcal: 200, 
		f_carbs: 500, 
		s_carbs: 50, 
		t_carbs: 200, 
		f_fat: 50,
		s_fat: 10,
		t_fat: 70,
		f_protein: 90, 
		s_protein: 30, 
		t_protein: 50, 
		photo1: 'assets/img/meal2.png', 
		photo2: 'assets/img/meal1.png',
		photo3: 'assets/img/photo1.png',
		doneState1: false,
		doneState2: true,
		doneState3: false,
		change1: false,
		change2: false,
		change3: false
	},
	{ 
		id: 4,
		date: 'Thursday, 24 June',
		name:'',
		s_calories:0,
		s_carb:0,
		f_kcal: 30,
		s_kcal: 100, 
		t_kcal: 200, 
		f_carbs: 500, 
		s_carbs: 50, 
		t_carbs: 200, 
		f_fat: 50,
		s_fat: 10,
		t_fat: 70,
		f_protein: 90, 
		s_protein: 30, 
		t_protein: 50,  
		photo1: 'assets/img/photo1.png', 
		photo2: 'assets/img/meal2.png',
		photo3: 'assets/img/meal5.png',
		doneState1: true,
		doneState2: false,
		doneState3: true,
		change1: false,
		change2: false,
		change3: false
	},
	{ 
		id: 5,
		date: 'Friday, 25 June',
		name:'',
		s_calories:0,
		s_carb:0,
		f_kcal: 30,
		s_kcal: 100, 
		t_kcal: 200, 
		f_carbs: 500, 
		s_carbs: 50, 
		t_carbs: 200, 
		f_fat: 50,
		s_fat: 10,
		t_fat: 70,
		f_protein: 90, 
		s_protein: 30, 
		t_protein: 50,  
		photo1: 'assets/img/meal3.png', 
		photo2: 'assets/img/meal5.png',
		photo3: 'assets/img/photo1.png',
		doneState1: false,
		doneState2: true,
		doneState3: false,
		change1: false,
		change2: false,
		change3: false
	},
	{ 
		id: 6,
		date: 'Saturday, 26 June',
		name:'',
		s_calories:0,
		s_carb:0,
		f_kcal: 50,
		s_kcal: 60, 
		t_kcal: 300, 
		f_carbs: 400, 
		s_carbs: 20, 
		t_carbs: 700, 
		f_fat: 100,
		s_fat: 50,
		t_fat: 20,
		f_protein: 110, 
		s_protein: 115, 
		t_protein: 50, 
		photo1: 'assets/img/meal1.png', 
		photo2: 'assets/img/meal5.png',
		photo3: 'assets/img/meal3.png',
		doneState1: false,
		doneState2: true,
		doneState3: false,
		change1: false,
		change2: false,
		change3: false
	}

];