export class Setting {
    id: number;
    email: string;
    sku: string;
    first_name: string;
    last_name: string;
    gender: string;
    date_of_birth: string;
    avatar_path: string;
    workouts_per_week: number;
    experience_level: string;
    time_per_workout: number;
    using_circuits: boolean;
    unit_system: number;
    language: string;
    height: number;
    inch: number;
    weight: number;
    current_weight: number;
    goal: number;
    goal_weight:string;
    days: number;
    meals: number;
    dietary_requirements: string;
    dairy: string;
    carbohydrates: string;
    protein: string;
    vegetables: string;
    fats: string;
    fruit: string;
    injuries: string;
}
