import { Workout } from './workout';

export const WORKOUTS : Workout[] = [
	{
		gnname: 'superset',
		name: 'back squats',
		sets: 5,
		reps: 10,
		sec: 0,
		moreInfo: false,
		moreInfo2: false,
		moreInfo3: false,
		doneState: false,
		doneState2: false,
		doneState3: false,
		descr: 'Description for squats',
		descr2: 'Description for squats',
		descr3: 'Description for squats',
		photo: 'assets/img/back_squats.png',
		photo2: 'assets/img/back_squats.png',
		photo3: 'assets/img/back_squats.png'
	},
	{
		gnname: 'circuit',
		name: 'curtsy lunges',
		sets: 3,
		reps: 16,
		sec: 0,
		moreInfo: false,
		moreInfo2: false,
		moreInfo3: false,
		doneState: false,
		doneState2: false,
		doneState3: false,
		descr: 'Description for curtsy lunges',
		descr2: 'Description for curtsy lunges',
		descr3: 'Description for curtsy lunges',
		photo: 'assets/img/curtsy_lunges.png',
		photo2: 'assets/img/curtsy_lunges.png',
		photo3: 'assets/img/curtsy_lunges.png'
	},
	{
		gnname: '',
		name: 'BB Romanian Deadlift ',
		sets: 3,
		reps: 4,
		sec: 0,
		moreInfo: false,
		moreInfo2: false,
		moreInfo3: false,
		doneState: false,
		doneState2: false,
		doneState3: false,
		descr: 'Description for bb romanian deadlift ',
		descr2: 'Description for bb romanian deadlift ',
		descr3: 'Description for bb romanian deadlift ',
		photo: 'assets/img/bb_romanian_deadlift.png',
		photo2: '',
		photo3: ''
	},
	{
		gnname: '',
		name: 'Cable Kickbacks',
		sets: 3,
		reps: 20,
		sec: 0,
		moreInfo: false,
		moreInfo2: false,
		moreInfo3: false,
		doneState: false,
		doneState2: false,
		doneState3: false,
		descr: 'Description for cable kickbacks ',
		descr2: 'Description for cable kickbacks ',
		descr3: 'Description for cable kickbacks ',
		photo: 'assets/img/cable_kickbacks.png',
		photo2: '',
		photo3: ''
	},
	{
		gnname: '',
		name: 'KB Swings',
		sets: 0,
		reps: 50,
		sec: 0,
		moreInfo: false,
		moreInfo2: false,
		moreInfo3: false,
		doneState: false,
		doneState2: false,
		doneState3: false,
		descr: 'Description for kb swings ',
		descr2: 'Description for kb swings ',
		descr3: 'Description for kb swings ',
		photo: 'assets/img/kb_swings.png',
		photo2: '',
		photo3: ''
	}
];